server:
  servlet:
    context-path: /api/v1 # URL base para la aplicación
  port: 8090
spring:
  application:
    name: tablon-mensajes # Nombre de la aplicación
  profiles:
    active: dev
  datasource:
    hikari:
      maximum-pool-size: 10         # Máximo número de conexiones en el pool.
      minimum-idle: 5              # Número mínimo de conexiones ociosas en el pool.
      idle-timeout: 30000          # Tiempo máximo que una conexión puede estar ociosa (en ms).
      max-lifetime: 1800000        # Tiempo máximo que una conexión puede estar en uso antes de ser cerrada (en ms).
      connection-timeout: 30000    # Tiempo máximo para esperar una conexión antes de lanzar una excepción (en ms).
      validation-timeout: 5000     # Tiempo máximo para validar una conexión antes de devolverla (en ms).
